dist: trusty
language: python

sudo: false
matrix:
    include:
        - python: 3.14
          env: TOXENV=py314
          dist: xenial
          sudo: true

install:
    - travis_retry pip install tox

script:
    - tox
